"""편차 추출 단계에서 공유하는 경로와 경험적 검출 임계값."""

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
SAMPLE_DIR = ROOT_DIR / "data" / "sample"
INTERMEDIATE_DIR = ROOT_DIR / "data" / "intermediate"

DEVIATION_MAP_PATH = INTERMEDIATE_DIR / "deviation_map.png"
ZERO_LINE_MASK_PATH = INTERMEDIATE_DIR / "zero_line_mask.png"
OUTPUT_CSV_PATH = INTERMEDIATE_DIR / "deviation_points.csv"
DEBUG_IMAGE_PATH = INTERMEDIATE_DIR / "deviation_points_debug.png"

VLM_MODEL_ID = "Qwen/Qwen2.5-VL-3B-Instruct"
VLM_BATCH_SIZE = 8
VLM_MIN_CROP_HEIGHT = 96
VLM_MAX_CROP_SCALE = 4.0

# remove_labels.py와 같은 export 형식을 기준으로 한 라벨 박스 검출값이다.
# 짧은 변이 REFERENCE_SHORT_SIDE보다 큰 이미지는 상한과 거리만 비례 확대한다.
REFERENCE_SHORT_SIDE = 720
FOREGROUND_THRESHOLD = 20
SCAN_MIN_AREA_RATIO = 0.01

LABEL_MIN_WIDTH = 24
LABEL_MAX_WIDTH = 90
LABEL_MIN_HEIGHT = 18
LABEL_MAX_HEIGHT = 58
LABEL_MIN_ASPECT = 1.0
LABEL_MAX_ASPECT = 5.0
LABEL_MIN_COMPONENT_AREA = 100
LABEL_RED_MIN_FILL_RATIO = 0.40
LABEL_OUTLINE_MIN_EXTENT = 0.62
LABEL_DUPLICATE_IOU = 0.70

# 빨간 채움과 중간 회색 외곽선이 주 검출 신호다. 검은 외곽선은 기존 입력과
# 합성 테스트를 위한 보조 신호로만 사용한다.
LABEL_RED_MIN_RED = 235
LABEL_RED_MAX_GREEN = 55
LABEL_RED_MAX_BLUE = 55
LABEL_GRAY_MIN = 145
LABEL_GRAY_MAX = 165
LABEL_GRAY_MAX_CHANNEL_DELTA = 4
# 흰 라벨의 안티앨리어싱/압축된 회색 테두리는 더 넓게 받되 내부 숫자를 요구한다.
LABEL_NEUTRAL_MIN = 105
LABEL_NEUTRAL_MAX = 225
LABEL_NEUTRAL_MAX_CHANNEL_DELTA = 16
LABEL_NEUTRAL_OUTLINE_MIN_EXTENT = 0.55
LABEL_NEUTRAL_MIN_TEXT_PIXELS = 6
# 테두리가 잘리거나 끊긴 흰 라벨은 밝은 내부+숫자+실제 리더의 조합으로 보완한다.
LABEL_LIGHT_FILL_MIN = 220
LABEL_LIGHT_FILL_MAX_CHANNEL_DELTA = 18
LABEL_LIGHT_FILL_OPEN_KERNEL = 5
LABEL_LIGHT_FILL_MIN_WIDTH = 20
LABEL_LIGHT_FILL_MAX_WIDTH = 86
LABEL_LIGHT_FILL_MIN_HEIGHT = 14
LABEL_LIGHT_FILL_MAX_HEIGHT = 54
LABEL_LIGHT_FILL_MIN_RATIO = 0.55
LABEL_LIGHT_FILL_MIN_TEXT_PIXELS = 8
LABEL_LIGHT_FILL_PADDING = 2
LABEL_DARK_MAX_VALUE = 95
LABEL_DARK_MAX_CHANNEL_DELTA = 18
LABEL_INNER_BOX_MAX_WIDTH = 55
LABEL_INNER_BOX_MAX_HEIGHT = 32
LABEL_TEXT_MIN_PIXELS = 8
LABEL_NORMALIZE_MARGIN = 6

# 정확한 파란 중심선을 우선 사용하고, 찾지 못한 라벨에만 완화 마스크를 쓴다.
LEADER_BLUE_MIN = 225
LEADER_OTHER_MAX = 70
LEADER_LOCAL_WINDOW = 7
LEADER_STRICT_LOCAL_PIXELS = 14
LEADER_RELAXED_LOCAL_PIXELS = 35
LEADER_WIDE_REGION_KERNEL = 5
LEADER_BOX_REACH_RATIO = 0.012
LEADER_BOX_REACH_MIN = 8
LEADER_MAX_BOX_GAP = 4
LEADER_MIN_COMPONENT_AREA = 5
LEADER_MIN_COMPONENT_SPAN = 6
LEADER_MAX_AREA_RATIO = 0.006
MEASUREMENT_POINT_RADIUS_RATIO = 0.004
MEASUREMENT_POINT_RADIUS_MIN = 3

# 아래 Hough 값은 기존 보조 함수 호출과 테스트를 위한 하위 호환용이다.
LEADER_LINE_HSV_LOWER = (100, 60, 60)
LEADER_LINE_HSV_UPPER = (130, 255, 255)
LEADER_ANCHOR_RADIUS = 10
MAX_LEADER_LINE_LEN = 260
HOUGH_THRESHOLD = 12
HOUGH_MIN_LINE_LENGTH = 8
HOUGH_MAX_LINE_GAP = 4

# ROI가 없으면 실제 범례 대신 지정한 Matplotlib 컬러맵으로 교차검증한다.
COLORBAR_ROI: tuple[int, int, int, int] | None = None
COLORBAR_MIN_MM = -3.0
COLORBAR_MAX_MM = 3.0
FALLBACK_COLORMAP = "jet"
CROSS_CHECK_MISMATCH_MM = 1.0
CROSS_CHECK_SAMPLE_INNER_RADIUS = 2
CROSS_CHECK_SAMPLE_OUTER_RADIUS = 7
